# Generated by Django 5.1 on 2024-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('area', models.FloatField()),
                ('official_languages', models.TextField()),
                ('continent', models.CharField(max_length=100)),
                ('major_cities', models.TextField()),
                ('climate', models.TextField()),
                ('gdp', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
